### ISSUE TITLE
Get notifications when subscribed libraries are updated

### ISSUE THREAD

**Issue by omederos** [librariesio/lib2slack#18]
`lib2slack` works great when I want to be notified about new gems of repositories being watching/monitored, but sometimes I have zero repos monitored but I'm manually subscribed to library releases.

Is it possible to extend `lib2slack` to get Slack notifications whenever one of my subscribed libraries are updated, instead of having to start monitoring repositories?

I'm willing to contribute if you kindly provide me the best way of doing this (an idea). I'm new with libraries.io and lib2slack, but I've been writing code in ruby/rails for a while.

**Comment by andrew** [comment]
Ah yeah, good catch, the web hooks currently only work on a repo level, we need some kind of account level web hooks too

**Comment by andrew** [comment]
I wonder if in the short term the rss feed could be used to power the slackbot?

**Comment by omederos** [comment]
Definitely! I didn't know there was an RSS to syndicate all my subscribed packages. I only saw that option on each package section, but I just found it at the end of the homepage :+1: 

Does this issue still make sense?

**Comment by andrew** [comment]
@omederos there's a slackbot that can take rss already here: https://bathruby.slack.com/apps/A0F81R7U7-rss

**Comment by andrew** [comment]
Going to close this for now
